version: "3" 

services:
  database:
    image: kartoza/postgis
    environment:
      - ALLOW_IP_RANGE=0.0.0.0/0
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=docker
    volumes:
      - treekit_db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - treekit
  api:
    build:
      context: ./api 
      dockerfile: Dockerfile 
    ports:
      - 3001:3000
    expose:
      - 3000
    networks:
      - treekit
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - PGHOST=database
      - PGPPORT=5432
      - PGPASSWORD=docker
      - PGUSER=docker
      - PGDATABASE=docker
  tiler:
    build:
      context: ./tiler
      dockerfile: Dockerfile
    volumes:
      - ./tiler:/src
      - /src/node_modules
    expose:
      - "8886"
    ports:
      - "8886:8886"
    depends_on:
      - database
    environment:
      - PGHOST=database
      - PGPPORT=5432
      - PGPASSWORD=docker
      - PGUSER=docker
    networks:
      - treekit

  reverse-proxy:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./proxy/nginx.config:/etc/nginx/nginx.conf
    networks:
      - treekit
    depends_on:
      - api
      - frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - treekit
    expose:
      - 3000
    ports:
      - 3010:3000

networks:
  treekit:
volumes:
  treekit_db_data:

