version: 2
jobs:
  build:
    machine: true
    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Build images
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
            echo 'export TAG=0.1.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
            echo 'building with tag TAG=0.1.${CIRCLE_BUILD_NUM}'
            TAG=0.1.${CIRCLE_BUILD_NUM} docker-compose -f docker-compose-production.yml build 
            TAG=0.1.${CIRCLE_BUILD_NUM} docker-compose -f docker-compose-production.yml push
      - run:
          name: Deploy 
          command: |
            scp docker-compose-production.yml root@$host:~/docker-compose.yml
            export 'DOCKER_HOST=$host'
            docker-compose pull 
            docker-compose up -d 
