version: 2
jobs:
  build:
    machine: true
    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Build images
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
            echo 'export TAG=0.1.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
            echo 'building with tag TAG=0.1.${CIRCLE_BUILD_NUM}'
            TAG=0.1.${CIRCLE_BUILD_NUM} docker-compose -f docker-compose-production.yml build 
            TAG=0.1.${CIRCLE_BUILD_NUM} docker-compose -f docker-compose-production.yml push
      - run:
          name: Deploy 
          command: |
            scp docker-compose-deploy.yml root@${OCEAN_HOST_IP}:~/docker-compose.yml
            ssh root@${OCEAN_HOST_IP} "TAG=0.1.${CIRCLE_BUILD_NUM} docker-compose down "
            ssh root@${OCEAN_HOST_IP} "TAG=0.1.${CIRCLE_BUILD_NUM} docker-compose up -d"
      - run:
          name: Populate DB 
          command: |
            scp data.tar.gz root@${OCEAN_HOST_IP}:~/data.tar.gz
            scp populate_data.sh root@${OCEAN_HOST_IP}:~/populate_data.sh
            ssh root@${OCEAN_HOST_IP} "tar xzvf data.tar.gz"
            ssh root@${OCEAN_HOST_IP} " TAG=0.1.${CIRCLE_BUILD_NUM} ./populate_data.sh"

